<?php

namespace PK\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{
    public function luNotification($id) {
        $qb = $this->createQueryBuilder('a')
                ->update()
                ->set('a.lu', true)
                ->where('a.id = :id')
                ->setParameter('id', $id);

        return $qb->getQuery()->execute();
    }
    
    public function luTouteNotification($user) {
        $qb = $this->createQueryBuilder('a')
                ->update()
                ->set('a.lu', true)
                ->where('a.user = :user')
                ->setParameter('user', $user);

        return $qb->getQuery()->execute();
    }
}
