<?php

namespace PK\PretBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HashMailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HashMailRepository extends EntityRepository
{
}
