<?php

namespace PK\ObjetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ObjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjetRepository extends EntityRepository
{
    public function getObjetAvecPretEnCours($id) {
        $qb = $this->createQueryBuilder('a')
                ->leftJoin('a.prets', 'c')
                ->addSelect('c')
                ->where('a.id = :id and c.rendu = 0')
                ->setParameter('id', $id);

        return $qb->getQuery()->getOneOrNullResult();
    }
    
    public function getObjetsBySearchCriteria($searchEntry) {
        $qb = $this->createQueryBuilder('a') 
                ->where('(a.titre LIKE :searchEntry OR a.description LIKE :searchEntry) AND a.actif = 1')
                ->setParameter('searchEntry', '%'.$searchEntry.'%')
                ->orderBy('a.titre', 'asc');

        return $qb->getQuery()
                        ->getResult();
    }
}
